[package]
name = "ddns-update"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]

[dependencies]
env_logger = "0.5.3"
json = "0.11"
log = "0.4.1"
structopt = "0.2"

[dependencies.chttp]
version = "0.1.3"
features = ["json"]
